const rootElementCards = $("#cards")[0];
const allSelect = $(".offers-filter > select").toArray();
const imgEl = $("#sort-img")[0];
const checkBox = $(".offers-sub-filters-instant > .container-checkbox > input")[0];
const optionsSort = $("select[name=offers-sub-filters-sorted-option]")[0];
let newArray;
const cards = [{
        year: 2019,
        img: "./img/cars/tiguan.png",
        nameCar: "Volkswagen Tiguan",
        mileage: "19.855",
        transmission: "Automatic",
        engine: "Diesel",
        price: "34,888",
        newCar: false,
        invaliable: true,
        date: 1
    },
    {
        year: 2014,
        img: "./img/cars/toyota.jpg",
        nameCar: "Toyota Highlander XLE",
        mileage: "69.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "27,875",
        newCar: true,
        invaliable: true,
        date: 2
    },
    {
        year: 2017,
        img: "./img/cars/lexus.jpg",
        nameCar: "Lexus RX 350 LUXURY",
        mileage: "39.850",
        transmission: "Automatic",
        engine: "Gas",
        price: "38,775",
        newCar: false,
        invaliable: true,
        date: 3
    },
    {
        year: 2016,
        img: "./img/cars/highlander4.jpg",
        nameCar: "Toyota Highlander LE A...",
        mileage: "104.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "23,728",
        newCar: false,
        invaliable: true,
        date: 4
    },
    {
        year: 2017,
        img: "./img/cars/elantra.jpg",
        nameCar: "Hyundai Elantra",
        mileage: "95.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "11,788",
        newCar: false,
        invaliable: true,
        date: 5
    },
    {
        year: 2016,
        img: "./img/cars/gle.jpg",
        nameCar: "Mercedes-Benz GLE-Cl...",
        mileage: "59.800",
        transmission: "Automatic",
        engine: "Diesel",
        price: "38,878",
        newCar: false,
        invaliable: true,
        date: 6
    },
    {
        year: 2015,
        img: "./img/cars/sold_venza.jpg",
        nameCar: "Toyota Venza AWD XLE...",
        mileage: "99.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "18,620",
        newCar: false,
        invaliable: false,
        date: 7,
        sold: true
    },
    {
        year: 2016,
        img: "./img/cars/lexus_sport.png",
        nameCar: "Lexus RX 350 F-SPORT",
        mileage: "86.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "34,888",
        newCar: true,
        invaliable: true,
        date: 8
    },
    {
        year: 2019,
        img: "./img/cars/tiguan.png",
        nameCar: "Volkswagen Tiguan",
        mileage: "19.855",
        transmission: "Automatic",
        engine: "Diesel",
        price: "34,888",
        newCar: false,
        invaliable: true,
        date: 9
    },
    {
        year: 2014,
        img: "./img/cars/toyota.jpg",
        nameCar: "Toyota Highlander XLE",
        mileage: "69.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "27,875",
        newCar: false,
        invaliable: true,
        date: 10
    },
    {
        year: 2017,
        img: "./img/cars/lexus.jpg",
        nameCar: "Lexus RX 350 LUXURY",
        mileage: "39.850",
        transmission: "Automatic",
        engine: "Gas",
        price: "38,775",
        newCar: false,
        invaliable: true,
        date: 11
    },
    {
        year: 2016,
        img: "./img/cars/highlander4.jpg",
        nameCar: "Toyota Highlander LE A...",
        mileage: "104.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "23,728",
        newCar: false,
        invaliable: true,
        date: 12
    },
    {
        year: 2019,
        img: "./img/cars/tiguan.png",
        nameCar: "Volkswagen Tiguan",
        mileage: "19.855",
        transmission: "Automatic",
        engine: "Diesel",
        price: "34,888",
        newCar: true,
        invaliable: true,
        date: 13
    },
    {
        year: 2014,
        img: "./img/cars/toyota.jpg",
        nameCar: "Toyota Highlander XLE",
        mileage: "69.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "27,875",
        newCar: false,
        invaliable: true,
        date: 14
    },
    {
        year: 2017,
        img: "./img/cars/lexus.jpg",
        nameCar: "Lexus RX 350 LUXURY",
        mileage: "39.850",
        transmission: "Automatic",
        engine: "Gas",
        price: "38,775",
        newCar: false,
        invaliable: true,
        date: 15
    },
    {
        year: 2016,
        img: "./img/cars/highlander4.jpg",
        nameCar: "Toyota Highlander LE A...",
        mileage: "104.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "23,728",
        newCar: false,
        invaliable: true,
        date: 16
    },
    {
        year: 2017,
        img: "./img/cars/elantra.jpg",
        nameCar: "Hyundai Elantra",
        mileage: "95.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "11,788",
        newCar: false,
        invaliable: true,
        date: 17
    },
    {
        year: 2016,
        img: "./img/cars/gle.jpg",
        nameCar: "Mercedes-Benz GLE-Cl...",
        mileage: "59.800",
        transmission: "Automatic",
        engine: "Diesel",
        price: "38,878",
        newCar: false,
        invaliable: true,
        date: 18
    },
    {
        year: 2015,
        img: "./img/cars/venza.png",
        nameCar: "Toyota Venza AWD XLE...",
        mileage: "99.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "18,620",
        newCar: false,
        invaliable: true,
        date: 19
    },
    {
        year: 2016,
        img: "./img/cars/lexus_sport.png",
        nameCar: "Lexus RX 350 F-SPORT",
        mileage: "86.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "34,888",
        newCar: true,
        invaliable: true,
        date: 20
    },
    {
        year: 2019,
        img: "./img/cars/tiguan.png",
        nameCar: "Volkswagen Tiguan",
        mileage: "86.000",
        transmission: "Automatic",
        engine: "Diesel",
        price: "34,888",
        newCar: false,
        invaliable: true,
        date: 21
    },
    {
        year: 2014,
        img: "./img/cars/toyota.jpg",
        nameCar: "Toyota Highlander XLE",
        mileage: "69.000",
        transmission: "Automatic",
        engine: "Gas",
        price: "27,875",
        newCar: false,
        invaliable: true,
        date: 22
    },
];